// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class C2sProtocol : ProtocolBase {
	public static  C2sProtocol Instance = new C2sProtocol();
	private C2sProtocol() {
		Protocol.SetProtocol<get> (get.Tag);
		Protocol.SetRequest<C2sSprotoType.get.request> (get.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetResponse<C2sSprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<set> (set.Tag);
		Protocol.SetRequest<C2sSprotoType.set.request> (set.Tag);

	}

	public class get {
		public const int Tag = 2;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class set {
		public const int Tag = 3;
	}

}