// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class S2cProtocol : ProtocolBase {
	public static  S2cProtocol Instance = new S2cProtocol();
	private S2cProtocol() {
		Protocol.SetProtocol<finish_achi> (finish_achi.Tag);
		Protocol.SetRequest<S2cSprotoType.finish_achi.request> (finish_achi.Tag);
		Protocol.SetResponse<S2cSprotoType.finish_achi.response> (finish_achi.Tag);

		Protocol.SetProtocol<heartbeat> (heartbeat.Tag);

		Protocol.SetProtocol<lilian_phy_power> (lilian_phy_power.Tag);
		Protocol.SetRequest<S2cSprotoType.lilian_phy_power.request> (lilian_phy_power.Tag);
		Protocol.SetResponse<S2cSprotoType.lilian_phy_power.response> (lilian_phy_power.Tag);

		Protocol.SetProtocol<lilian_result> (lilian_result.Tag);
		Protocol.SetRequest<S2cSprotoType.lilian_result.request> (lilian_result.Tag);
		Protocol.SetResponse<S2cSprotoType.lilian_result.response> (lilian_result.Tag);

		Protocol.SetProtocol<mail> (mail.Tag);
		Protocol.SetRequest<S2cSprotoType.mail.request> (mail.Tag);
		Protocol.SetResponse<S2cSprotoType.mail.response> (mail.Tag);

	}

	public class finish_achi {
		public const int Tag = 3;
	}

	public class heartbeat {
		public const int Tag = 1;
	}

	public class lilian_phy_power {
		public const int Tag = 4;
	}

	public class lilian_result {
		public const int Tag = 5;
	}

	public class mail {
		public const int Tag = 2;
	}

}