// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class SCProtocol : ProtocolBase {
	public static  SCProtocol Instance = new SCProtocol();
	private SCProtocol() {
		Protocol.SetProtocol<heartbeat> (heartbeat.Tag);

	}

	public class heartbeat {
		public const int Tag = 1;
	}

}